### ISSUE TITLE
Unit Tests for Milestone 2

### ISSUE THREAD

**Issue by balmas** [alpheios-project/morphlib#10]
Unit tests:
- [x] test language can be detected from an @xml:lang attribute on the selected element
- [x] test language can be detected from an @xml:lang attribute on the immediate parent element
- [x] test language can be detected from an @xml:lang attribute on an ancestor parent element 
- [x] test nearest ancestor's @xml:lang is used when a further ancestor also has an @xml:lang attribute
- [ ] test that the handler identifies the correct word for space-separated tokenization
- [ ] test that the handler identifies the correct word for character-separated tokenization
- [ ] test that backwards context is correctly identified for ltr text dir
- [ ] test that backwards context is correctly identified for rtl text dir
- [ ] test that forwards context is correctly identified for ltr text dir
- [ ] test that forwards context is correctly identified for rtl text dir
- [ ] test that backwards context is correctly identified for space-separated tokenization
- [ ] test that backwards context is correctly identified for space-separated tokenization
- [ ] test that forwards context is correctly identified for ltr character-separated tokenization
- [ ] test that forwards context is correctly identified for rtl character-separated tokenization
