### ISSUE TITLE
Unit Tests for Milestone 3

### ISSUE THREAD

**Issue by balmas** [alpheios-project/morphlib#14]
Unit tests for the morphology lookup method:
- [ ] test the language in the event object triggers the right lookup
- [ ] test the API parameter triggers the right parser method

Unit tests for the Tufts Morphology service Parser
- [ ] test that it returns the right form
- [ ] test that it returns the right lemmas
- [ ] test that it returns the right part of speech per lemma
- [ ] test that the order of the analyses is correct
- [ ] test that the order of the inflections is correct

**Comment by balmas** [comment]
@elijahjcooke I'll add my comments on the issues you were having with the unit tests here for lack of a better place.

1) I think if you want to be able to access modules that are imported into morphlib you need to either export them explicity from morphlib or else provide accessor functions to them.  They aren't automatically added into the module as accessible properties.  So, for example, if you wanted to be able to wire up a tokenresponse object from Qunit, one way to enable this would be to add a method such as the following in morphlib:

```
 // exposing tokenresponse for testing purposes
    makeTokenResponse(word,cfwd,cbwd,lang,dir) {
      return new tokenresponse(word,cfwd,cbwd,lang,dir);
    }
```

And similarly, to test a response from the morphservice:

```
// exposing morphresponse for testing purposes
    getMorphResponse(tokenobject) {
      morphservice(
        tokenobject,
        this.prefs.getmorphservicetype(this.currentlang),
        this.prefs.getmorphserviceuri(this.currentlang),
        this.prefs.getmorphserviceapiformat(this.currentlang),
        this.prefs.getmorphserviceversion(this.currentlang),
       this);
    }
```
This doesn't actually work that well though, because there are asynchronous calls to the service in there and, as the module is currently constructed, it doesn't return any object that you can use of to test the results directly. (To test, you will have to use QUnit's assert.async() function to stop and start the test execution while waiting for the async call to return.  

This is another reason that Thibault's suggestion to make it possible to override the async function is so important, because it would make testing easier -- you could have it return directly and avoid the need for asynchronous handling in the unit tests. You have the basic structure in place for that, but the morphservice module would need to be refactored a bit to enable actually overriding the async function.

In general, this is why it's better to start with unit tests of individual modules, building up to an integration test of the overall library, because as you try to test each module directly you will see what needs to be exposed for testing.

I think we are probably out of time for that now though so we can talk about what we can do on the weekly call tomorrow.
