### ISSUE TITLE
Unit Tests for Milestone 1

### ISSUE THREAD

**Issue by balmas** [alpheios-project/morphlib#9]
Unit tests:
- [ ] test activate method adds the default event listener
- [ ] test activate method adds a single client-supplied event listener
- [ ] test activate method adds multiple client-supplied event listeners 
- [ ] test deactivate method removes a single event listener 
- [ ] test deactivate method removes multiple event listeners
- [ ] test current language method returns the language which was activated
